### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Qzy568** [MMMU-Benchmark/MMMU#44]
您好，我想运行的代码infer_gpt.py，输入python infer/infer_gpt.py gpt-4o cot vision
但是报如下错误，报错函数在vision_mmmu_doc_to_visual(doc)
Generating train split: 1730 examples [00:03, 455.85 examples/s]
Begin processing vision
Processing vision:   0%|                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 225, in <module>
    main()
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 221, in main
    run_and_save()
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 216, in run_and_save
    temp_files.append(process_and_save_part(dataset, SETTING, model_components))
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 207, in process_and_save_part
    result, data = future.result()
  File "/root/miniconda3/envs/humanevalv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/miniconda3/envs/humanevalv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/humanevalv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 172, in process_prompt
    images = vision_mmmu_doc_to_visual(data)
  File "/workspace/mm_eval/qzy/code/MMMU/mmmu-pro/infer/infer_gpt.py", line 71, in vision_mmmu_doc_to_visual
    return [doc['image']]
TypeError: string indices must be integers

**Comment by Qzy568** [comment]
请问，如果本地加载数据集需要如何设置呢

**Comment by Zheng0428** [comment]
以infer_gpt.py举例子，正常加载数据是在这一行[line](https://github.com/MMMU-Benchmark/MMMU/blob/6ce42f4d8f70c1841c67867152648974415b5cac/mmmu-pro/infer/infer_gpt.py#L184)，只需要把'MMMU/MMMU_Pro'替换成你本地的数据集路径就可以加载了。希望可以帮助到你

**Comment by Qzy568** [comment]
请问，如果SETTING 为 standard，没有用到prompts.yaml里的提示词吗？，我看在infer_gpt.py里process_prompt函数只有SETTING == 'vision'的情况使用了 
def process_prompt(data, model_components):
    if 'standard' in SETTING:
        prompt = mmmu_doc_to_text(data)
        images = origin_mmmu_doc_to_visual(data)
    elif SETTING == 'vision':
        prompt = prompt_config['vision']
        images = vision_mmmu_doc_to_visual(data)

    return infer({"prompt": prompt, "images": images}, max_tokens=4096, **model_components), data
